Models/ErrorViewModel.cs
namespace Quiz_Management.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Quiz_Management.Models;
using System.Diagnostics;

namespace Quiz_Management.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult DataTable()
        {
            return View();
        }

        public IActionResult QuizTable()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }


}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace Quiz_Management.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;

namespace Quiz_Management.Controllers
{
    public class QuestionController : Controller
    {
        public IActionResult QuestionTable()
        {
            return View();
        }
    }
}

Controllers/QuestionLevelController.cs
using Microsoft.AspNetCore.Mvc;

namespace Quiz_Management.Controllers
{
    public class QuestionLevelController : Controller
    {
        public IActionResult QuestionLevelTable()
        {
            return View();
        }
    }
}

Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;

namespace Quiz_Management.Controllers
{
    public class QuizController : Controller
    {
        public IActionResult QuizTable()
        {
            return View();
        }
    }
}

Controllers/QuizWiseQuestionsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Quiz_Management.Controllers
{
    public class QuizWiseQuestionsController : Controller
    {
        public IActionResult QuizWiseQuestionsTable()
        {
            return View();
        }
    }
}

Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;

namespace Quiz_Management.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult Registration()
        {
            return View();
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace Quiz_Management.Controllers
{
    public class UserController : Controller
    {
        public IActionResult UserTable()
        {
            return View();
        }

        public IActionResult UserUpdate()
        {
            return View();
        }
    }
}

Views/Home/Blank.cshtml
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Blank Page</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item">Pages</li>
                <li class="breadcrumb-item active">Blank</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-6">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Example Card</h5>
                        <p>This is an examle page with no contrnt. You can use it as a starter for your custom pages.</p>
                    </div>
                </div>

            </div>

            <div class="col-lg-6">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Example Card</h5>
                        <p>This is an examle page with no contrnt. You can use it as a starter for your custom pages.</p>
                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->

Views/Login/Login.cshtml
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
<main>
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">

        <title>Dashboard - Quiz Management Bootstrap Template</title>
        <meta content="" name="description">
        <meta content="" name="keywords">

        <!-- Favicons -->
        <link href="~/img/favicon.png" rel="icon">
        <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

        <!-- Google Fonts -->
        <link href="https://fonts.gstatic.com" rel="preconnect">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

        <!-- Vendor CSS Files -->
        <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
        <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
        <link href="~/vendor/quill/quill.snow.css" rel="stylesheet">
        <link href="~/vendor/quill/quill.bubble.css" rel="stylesheet">
        <link href="~/vendor/remixicon/remixicon.css" rel="stylesheet">
        <link href="~/vendor/simple-datatables/style.css" rel="stylesheet">

        <!-- Template Main CSS File -->
        <link href="~/css/style.css" rel="stylesheet">
        @*  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/AddressBook.styles.css" asp-append-version="true" /> *@
    </head>
    <div class="container">
        <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
                        <div class="d-flex justify-content-center py-4">
                            <a href="~/" class="logo d-flex align-items-center w-auto">
                                <img src="~/img/apple-touch-icon.png" />
                                <span class="d-none d-lg-block">Quiz Management System</span>
                            </a>
                        </div>
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="pt-4 pb-2">
                                    <h5 class="card-title text-center pb-0 fs-4">Login To Your Account</h5>
                                    <p class="text-center small">Enter your Username and Password to Login</p>
                                </div>
                                <form class="row g-3 needs-validation" method="post" asp-action="Index" asp-controller="Home">
                                    <div class="col-12">
                                        <label for="yourUsername" class="form-label">Username</label>
                                        <div class="input-group has-validation">
                                            <input type="text" name="username" class="form-control" id="yourUsername" required>
                                            <div class="invalid-feedback">Please choose a username.</div>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <label for="yourPassword" class="form-label">Password</label>
                                        <input type="password" name="password" class="form-control" id="yourPassword" required>
                                        <div class="invalid-feedback">Please enter your password!</div>
                                    </div>
                                    
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100" type="submit">Login</button>
                                    </div>
                                    <div class="col-12">
                                        <p class="small mb-0">Don't have an account? <a asp-controller="Registration" asp-action="Registration">Create an account</a></p>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</main>

Views/Question/QuestionTable.cshtml
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Question List</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item">Databases</li>
                <li class="breadcrumb-item active">Question</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card w-100" style="overflow-x: auto; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
                    <div class="card-body">

                        <!-- Table with stripped rows -->
                        <table class="table datatable" style="width: 100%; border-collapse: collapse;">
                            <thead>
                                <tr>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">QuestionID</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">QuestionText</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">QuestionLevelID</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">OptionA</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">OptionB</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">OptionC</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">OptionD</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">CorrectOption</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">QuestionMarks</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">IsActive</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">UserID</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">Created</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">Modified</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">Operation</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>What Is Node.JS ?</td>
                                    <td>1</td>
                                    <td>Framework</td>
                                    <td>Library</td>
                                    <td>Software</td>
                                    <td>Language</td>
                                    <td>Framework</td>
                                    <td>1</td>
                                    <td>Yes</td>
                                    <td>1</td>
                                    <td>05-01-2025</td>
                                    <td>05-01-2025</td>
                                    <td>
                                        <center>
                                            <button style="background: none; border: none">

                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                                                </svg>
                                            </button>

                                            <button style="background: none; border: none">
                                                <svg xmlns="http://www.w3.org/2000/svg" onclick="delete()" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
                                                </svg>
                                            </button>
                                        </center>
                                    </td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>What Is Python ?</td>
                                    <td>2</td>
                                    <td>Framework</td>
                                    <td>Library</td>
                                    <td>Software</td>
                                    <td>Language</td>
                                    <td>Language</td>
                                    <td>1</td>
                                    <td>Yes</td>
                                    <td>2</td>
                                    <td>05-01-2025</td>
                                    <td>05-01-2025</td>
                                    <td>
                                        <center>
                                            <button style="background: none; border: none">

                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                                                </svg>
                                            </button>

                                            <button style="background: none; border: none">
                                                <svg xmlns="http://www.w3.org/2000/svg" onclick="delete()" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
                                                </svg>
                                            </button>
                                        </center>
                                    </td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>What is SQL ?</td>
                                    <td>3</td>
                                    <td>Sequenced Query Language</td>
                                    <td>Standard Query Language</td>
                                    <td>Structured Query Language</td>
                                    <td>None Of The Above</td>
                                    <td>Structured Query Language</td>
                                    <td>1</td>
                                    <td>No</td>
                                    <td>3</td>
                                    <td>05-01-2025</td>
                                    <td>05-01-2025</td>
                                    <td>
                                        <center>
                                            <button style="background: none; border: none">

                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                                                </svg>
                                            </button>

                                            <button style="background: none; border: none">
                                                <svg xmlns="http://www.w3.org/2000/svg" onclick="delete()" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
                                                </svg>
                                            </button>
                                        </center>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <!-- Add Question Button -->
                        <button type="button" class="btn btn-primary justify-content-end">
                            <a class="text-light" asp-controller="User" asp-action="UserUpdate">Add Question</a>
                        </button>

                    </div>
                </div>

            </div>
        </div>
    </section>

</main>

Views/QuestionLevel/QuestionLevelTable.cshtml
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Question Level</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item">Tables</li>
                <li class="breadcrumb-item active">QuestionLevel</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card w-100" style="overflow-x: auto; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
                    <div class="card-body">

                        <!-- Table with stripped rows -->
                        <table class="table datatable" style="width: 100%; border-collapse: collapse;">
                            <thead>
                                <tr>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;"><b>Q</b>uestionLevelID</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">QuestionLevel</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">UserID</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">Created</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">Modified</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td style="padding: 8px; border: 1px solid #ddd;">1</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">Easy</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">1</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">4/01/2025</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">4/01/2025</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px; border: 1px solid #ddd;">2</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">Medium</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">2</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">8/01/2025</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">8/01/2025</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px; border: 1px solid #ddd;">3</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">Hard</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">3</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">7/01/2025</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">7/01/2025</td>
                                </tr>
                            </tbody>
                        </table>
                        <button type="button" class="btn btn-primary justify-content-end">
                            <a class="text-light" asp-controller="Quiz" asp-action="QuizUpdate">Add Question Level</a>
                        </button>
                        <!-- End Table with stripped rows -->

                    </div>
                </div>

            </div>
        </div>
    </section>

</main>

Views/QuizWiseQuestions/QuizWiseQuestionsTable.cshtml
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Quiz Wise Question</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item">Tables</li>
                <li class="breadcrumb-item active">QuestionLevel</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card w-100" style="overflow-x: auto; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
                    <div class="card-body">

                        <!-- Table with stripped rows -->
                        <table class="table datatable" style="width: 100%; border-collapse: collapse;">
                            <thead>
                                <tr>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;"><b>Q</b>uizWiseQuestionsID</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">QuizID</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">QuestionID</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">UserID</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">Created</th>
                                    <th style="padding: 8px; border: 1px solid #ddd; background-color: #f4f4f4;">Modified</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td style="padding: 8px; border: 1px solid #ddd;">1</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">2</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">3</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">2</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">4/01/2025</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">4/01/2025</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px; border: 1px solid #ddd;">2</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">3</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">4</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">5</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">4/01/2025</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">4/01/2025</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px; border: 1px solid #ddd;">3</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">4</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">5</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">7</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">4/01/2025</td>
                                    <td style="padding: 8px; border: 1px solid #ddd;">4/01/2025</td>
                                </tr>
                            </tbody>
                        </table>
                        <button type="button" class="btn btn-primary justify-content-end">
                            <a class="text-light" asp-controller="Quiz" asp-action="QuizUpdate">Add Quiz Wise Question</a>
                        </button>
                        <!-- End Table with stripped rows -->

                    </div>
                </div>

            </div>
        </div>
    </section>

</main>

Views/Shared/_LayoutLogin.cshtml
<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard - Quiz Management Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
    @*  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AddressBook.styles.css" asp-append-version="true" /> *@
</head>
<body>
    @RenderBody()
</body>
</html>